apiVersion: v1
kind: Service
metadata:
 name: microservice-service
 metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"   # OR "classic"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  selector:
   app: microservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer